name: agentbench
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - pydantic
  - langchain
  - langgraph
  - txtai
  - openai
  - ollama
  - wandb
 
  - pip:
      - python-dotenv
      - transformers
      - pydantic-ai
      - crewai
      - wandb
      - langsmith
      - semantic_kernel
      - autogen-agentchat
      - streamlit
